project:
  type: website
  output-dir: docs
format:
  html:
    theme: cosmo
website:
  title: "Learning Analytics Methods"
  cookie-consent: true
  repo-url: https://github.com/lamethods/labook-code/
  google-analytics: "G-Y4VBV3J9WD"
  twitter-card: true
  site-url: https://lamethods.github.io
  open-graph: true
  navbar:
    title: "LA Methods"
    background: light
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "Learning Analytics Methods and Tutorials"
        href: book1/index.html
      - text: "Advanced Learning Analytics Methods"
        href: book2/index.html
resources:
  - CNAME

